# Generated by Django 3.0.7 on 2020-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
                ('race', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('birth', models.CharField(default=None, max_length=30)),
                ('spouse', models.CharField(default=None, max_length=70)),
                ('death', models.CharField(default=None, max_length=30)),
                ('realm', models.CharField(default=None, max_length=90)),
                ('hair', models.CharField(default=None, max_length=20)),
                ('wiki', models.CharField(default=None, max_length=90)),
            ],
        ),
    ]
