# Generated by Django 3.0.7 on 2020-06-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotr_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wiki',
        ),
        migrations.AddField(
            model_name='character',
            name='identifier',
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='lotr_v2.Race'),
        ),
    ]
